[[cn]]
name = "default"
dns = [
    "2001:4860:4860::8888#dns.google",
    "2620:fe::9#dns.quad9.net",
    "2606:4700:4700::1111#cloudflare-dns.com",
    "8.8.8.8#dns.google",
    "9.9.9.9#dns.quad9.net",
    "1.1.1.1#cloudflare-dns.com",
]
domains = [
    ".",
]

[[cn]]
name = "domestic"
dns = [
    "1.12.12.12@853#dot.pub",
    "120.53.53.53@853#dot.pub",
    "223.5.5.5@853#dns.alidns.com",
    "223.6.6.6@853#dns.alidns.com",
    "2400:3200::1@853#dns.alidns.com",
    "2400:3200:baba::1@853#dns.alidns.com",
]
domains = [
    "pi.wwan.buzz",
    "cn",
    "cdngslb.com",
    "ks-cdn.com",
    "ksyuncdn.com",

    "baidu.com",
    "bdimg.com",
    "bcebos.com",
    "bdstatic.com",
    "shifen.com",

    "jd.com",
    "360buyimg.com",
    "3.cn",
    "qianxun.com",
    "cdn20.com",
    "jcloud-cdn.com",
    "jcloudimg.com",
    "herdcloud.com",

    "zhihu.com",
    "zhimg.com",
    "ovscdns.com",
    "dnsv1.com",
    "chinaidcnet.com",

    "alibaba.com",
    "aliapp.org",
    "aliyun.com",
    "taobao.com",
    "www.taobao.com",
    "tbcache.com",
    "tmall.com",
    "alicdn.com",
    "mmstat.com",

    "bilibili.com",
    "hdslb.com",
    "bilicdn1.com",

    "smzdm.com",
    "qcloudcjgj.com",
    "zdmimg.com",

    "126.net",
    "127.net",
    "163.com",
    "163yun.com",
    "kunluncan.com",
    "kunlunca.com",
    "netease.com",
    "kunlunso.com",

    "anydesk.com",

    "douyin.com",
    "douyinpic.com",
    "douyinstatic.com",
    "douyinvod.com",
    "bytedance.com",
    "bytetos.com",
    "bytescm.com",
    "bytegoofy.com",
    "bytednsdoc.com",
    "edge-byted.com",
    "byteimg.com",
    "bytedns1.com",
    "queniuiq.com",
    "queniubg.com",
    "queniusz.com",
    "queniuum.com",
    "queniuyk.com",
    "queniusy.com",
    "queniuso.com",
    "fclouddns.net",

    "ixigua.com",
    "snssdk.com",
    "bdxiguastatic.com",

    "zijieapi.com",

    "alikunlun.com",
    "wsglb0.com",

    "uyun-cdn.com",

    "cdnhwc1.com",
    "cdnhwc2.com",

    "qingting.fm",

    "tencent.com",
    "tencent-cloud.com",
    "edgeonedy1.com",
]
