[[cn]]
name = "default"
dns = [
    "2001:4860:4860::8888#dns.google",
    "2620:fe::9#dns.quad9.net",
    "2606:4700:4700::1111#cloudflare-dns.com",
    "8.8.8.8#dns.google",
    "9.9.9.9#dns.quad9.net",
    "1.1.1.1#cloudflare-dns.com",
]
domains = [
    ".",
]

[[cn]]
name = "domestic"
dns = [
    "1.12.12.12@853#dot.pub",
    "120.53.53.53@853#dot.pub",
    "223.5.5.5@853#dns.alidns.com",
    "223.6.6.6@853#dns.alidns.com",
    "2400:3200::1@853#dns.alidns.com",
    "2400:3200:baba::1@853#dns.alidns.com",
]
domains = [
    "cn",

    "baidu.com",
    "bdimg.com",
    "bcebos.com",
    "bdstatic.com",

    "jd.com",
    "360buyimg.com",
    "3.cn",
    "qianxun.com",
    "cdn20.com",
    "jcloud-cdn.com",
    "jcloudimg.com",

    "zhihu.com",

    "alibaba.com",
    "aliapp.org",
    "aliyun.com",
    "taobao.com",
    "www.taobao.com",
    "tbcache.com",
    "tmall.com",
    "alicdn.com",
    "mmstat.com",
]
